### SHL Assessment Recommendation Test

POST https://shl-assessment-recommendation-system.onrender.com/recommend
Content-Type: application/json

{
  "query": "Looking for a backend developer with OAuth experience"
}
    